algoritmo "Interação com o Usúario"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Gustavo Guanabara
// Função : interação com o Usuario
// Autor :  Marivaldo Cordeiro
// Data : 22/03/2024
// Seção de Declarações 
var
   Nome: caractere

inicio
// Seção de Comandos
 escreval("Olá qual é o seu nome: ")
  leia(Nome)
  escreval("Olá ", Nome, " sejá bem-vindo!")

fimalgoritmo
