algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Função       :somar dois números e mostrar seu resultado
// Professor   :Gustavo Guanabara
// Author      :Marivaldo Cordeiro
// Data        :22/03/2024
var
n1, n2, s: inteiro
inicio
escreval("Digite um número: ")
leia(n1)
escreva("Digite outro número: ")
leia(n2)
s <- n1+n2
escreva("A soma entre ", n1, " e ",  n2, " é igual a: ",s)

fimalgoritmo